data_ingestion:
  test_size: 0.2

model:
  param_distributions:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5, 7, 9]
    learning_rate: [0.01, 0.05, 0.1]
    subsample: [0.7, 0.8, 1.0]
    colsample_bytree: [0.7, 0.8, 1.0]
    gamma: [0, 0.1, 0.2]
    reg_alpha: [0, 0.01, 0.1]
    reg_lambda: [1, 1.5, 2]